# POST http://localhost:5000/dossier/register HTTP/1.1
# Content-Type: application/json

# {
#   "nom": "John4",
#   "prenom": "Doe4",
#   "email": "john4@example.com",
#   "mot_de_passe": "aaaaaaaa",
#   "role": "admin",
#   "id_hopital": "148",
#   "autre_donnees": {
#     "info": "autre donnzz"
#   }
# }

// api pour la creation d un hopitale! 

# POST http://localhost:5000/dossier/addhopitale HTTP/1.1
# Content-Type: application/json

# {
#   "nom": "Hopital C",
#   "adresse": "123 Rue de l'Hopital V",
#   "type_hopitale": "Hopital",
#   "autres_donnees": "Donnees supplementaires",
#   "politique_gestion": "Politique de gestion"
# }

// api pour la creation d un personnel!

# POST http://localhost:5000/dossier/register HTTP/1.1
# Content-Type: application/json

# {
#   "nom": "John3",
#   "prenom": "Doe3",
#   "email": "john3@example.com",
#   "mot_de_passe": "aaaaaaaa",
#   "role": "admin",
#   "id_hopital": "147",
#   "autre_donnees": {
#     "info": "autre donnzz"
#   }
# }

# GET http://localhost:5000/dossier/getall


# POST http://localhost:5000/dossier/addpatient/148 HTTP/1.1
# Content-Type: application/json

# {
#   "nom": "marcel",
#   "prenom": "samia",
#   "date_naissance": "2004-01-01",
#   "age": "18",
#   "sexe": "Masculin",
#   "taille": "180",
#   "adresse": "123 Rue de l'Hopital V",
#   "nom_tuteur": "Tuteur2",
#   "photo": "photo2.jpg",
#   "id_utilisateur": "184",
#   "mot_de_passe": "aaaaaaaa",
#   "tel": "+237 620410454"
# }

# /
# POST https://medxchange-backend.onrender.com/dossier/login
# Content-Type: application/json

# {
#   "email": "john@example.com",
#   "mot_de_passe": "aaaaaaaa"
# }

POST http://localhost:5000/dossier/addpatient/148
Content-Type: application/json

{
  "nom": "marcel",
  "prenom": "samia",
  "date_naissance": "2004-01-01",
  "age": "18",
  "sexe": "Masculin",
  "taille": "180",
  "adresse": "123 Rue de l'Hopital V",
  "nom_tuteur": "Tuteur2",
  "photo": "photo2.jpg",
  "id_utilisateur": "182",
  "mot_de_passe": "aaaaaaaa",
  "tel": "+237620410454",
  "email": "ulrichhaman@gmail.com"
}